### ISSUE TITLE
Date and time is not pre-selected when clicking on a recurring event from the calendar

### ISSUE THREAD

**Issue by kieranklaassen** [GetOccasion/occsn-checkout#50]
Reported by: t@occsn.com
  
Reason for priority: Everything else

## Steps to reproduce

1. Go to https://app.getoccasion.com/p/stacks/1317/8575
2. Click on "Cooking class with Mary" for Sep 19.
3. The date and time is not preselected on the list of time slots.

## Expected behavior

The date and time selected from the calendar should be pre-selected from the list of time slots on the checkout page.

## Actual behavior

Time slot is not preselected

## Notes

https://secure.helpscout.net/conversation/656230415/22018/

**Comment by pelletencate** [comment]
Not a bug, expected by https://github.com/GetOccasion/occasion/issues/7220
