### ISSUE TITLE
Can't add multiple photos to modern checkout experience

### ISSUE THREAD

**Issue by kieranklaassen** [GetOccasion/occsn-checkout#52]
Reported by: t@occsn.com
  
Reason for priority: Everything else

## Steps to reproduce

From the listing editor click on the Images tab.
No option exists to add multiple images.

## Expected behavior

Option that would allow multiple images to be added to the same listing.

## Actual behavior

No such option.

## Notes

https://secure.helpscout.net/conversation/656235372/22019/

**Comment by pelletencate** [comment]
Not a bug, feature covered by https://github.com/GetOccasion/occasion/issues/6081
