### ISSUE TITLE
Customer name doesn't appear in the confirmation email subject or body

### ISSUE THREAD

**Issue by kieranklaassen** [GetOccasion/occsn-checkout#55]
Reported by: t@occsn.com
  
Reason for priority: Someone want this fixed real bad

## Steps to reproduce

When a booking is made and a confirmation email is sent to the merchant (me), the customer's name does not appear in the email subject and in the body of the email message.

## Expected behavior

The customer name

## Actual behavior

No customer name

## Notes

https://secure.helpscout.net/conversation/677576898

**Comment by pelletencate** [comment]
Closing in favor of https://github.com/GetOccasion/occasion/issues/7332
