### ISSUE TITLE
Email subject line is missing customer name

### ISSUE THREAD

**Issue by kieranklaassen** [GetOccasion/occsn-checkout#56]
Reported by: aksh@occsn.com
  
Reason for priority: Frequently used feature broken for all merchants

## Steps to reproduce

1. In the merchant confirmation email - the subject line is missing customer name

## Expected behavior

It should read "Ben just purchased Schedule a time with Aksh"

## Actual behavior

It actually reads "just purchased Schedule a time with Aksh"

## Notes

https://secure.helpscout.net/conversation/678353108

**Comment by pelletencate** [comment]
Closing in favor of https://github.com/GetOccasion/occasion/issues/7332
