### ISSUE TITLE
Difficulty ordering gift cards

### ISSUE THREAD

**Issue by kieranklaassen** [GetOccasion/occsn-checkout#64]
Reported by: aksh@occsn.com
  
Reason for priority: No customers can book

## Steps to reproduce

1. https://app.getoccasion.com/xp/llihu5a8
2. Try purchasing a GC

## Expected behavior

After selecting the amount, it should ask for me to enter my CC

## Actual behavior

It does not ask me for CC

## Notes

https://secure.helpscout.net/conversation/698793896

**Comment by pelletencate** [comment]
This is not supported, by design.
